version: '3.1'
services:
  stat-server:
    ports:
      - "9090:9090"
    depends_on:
      - stat-db

  stat-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=evilaks
      - POSTGRES_PASSWORD=password

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
